version: '3.8'
services: 
  commerce:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /.devcontainer/commerce.sh
    volumes:
      - ../..:/workspaces:cached
      - commerce:/var/www/html
      - ../.devcontainer:/.devcontainer
    env_file: commerce.localhost.env
    network_mode: service:db
  db:
    image: mysql:8.0-oracle
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
  redis:
    image: redis:latest
    network_mode: service:db
  ampq:
    image: rabbitmq:latest
    network_mode: service:db
  # mailhog:
  #   image: mailhog/mailhog
  #   network_mode: service:db  
  elasticsearch:
    image: elasticsearch:7.10.1
    network_mode: service:db
    environment:
      - discovery.type=single-node
volumes:
  db-data:
  commerce: